name: adaptix
description: A flexible and effective flutter package for responsive and adaptive design.
version: 0.1.0

repository: https://github.com/mcfugger/adaptixV2.git

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter
  meta: ^1.8.0
  

dev_dependencies:
  dart_code_metrics: ^4.17.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  


flutter:
